version: '3'
services:
  authentificationservice:
    build: ./externalservices/authentification
    ports:
      - "3001:3001"
    networks:
      - docker-kafka_blue-network

  paymentsystemservice:
    build: ./externalservices/paymentSystem
    ports:
      - "3007:3007"
    networks:
      - docker-kafka_blue-network

  ticketbookingservice:
    build: ./externalservices/ticketBooking
    ports:
      - "3004:3004"
    networks:
      - docker-kafka_blue-network

  traintelemetryservice:
    build: ./externalservices/trainTelemetry
    ports:
      - "3005:3005"
    networks:
      - docker-kafka_blue-network

  fraudetelemetryservice:
    build: ./externalservices/fraudTelemetry
    ports:
      - "3010:3010"
    networks:
      - docker-kafka_blue-network

  fraudcontrollerservice:
    build: ./fraud-controller
    ports:
      - "3006:3006"
    networks:
      - docker-kafka_blue-network

  statisticsservice:
    build: ./statistics
    ports:
      - "3009:3009"
    networks:
      - docker-kafka_blue-network

  ticketcheckservice:
    build: ./ticket-check
    ports:
      - "3003:3003"
    networks:
      - docker-kafka_blue-network

  ticketmanagerservice:
    build: ./ticket-manager
    ports:
      - "3011:3011"
    networks:
      - docker-kafka_blue-network

networks:
  docker-kafka_blue-network:
    external: true





